
name: Publish Docker image

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    run-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


      - name: Log into Docker image

      - name: Extract metadata(tags, labels) for Docker

      - name: Build and push Docker image